package storage

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Golden v7 fixtures are captured with the CURRENT writer, before the format
// bump, and committed. After the bump the writer emits v8 and these files are
// the only proof that a store written by an older binary still opens.
//
// Run with -run TestGenerateV7Fixtures -v and the env var set:
//
//	SIMDLOGS_WRITE_V7_FIXTURES=1 go test ./internal/storage -run TestGenerateV7Fixtures
//
// It is skipped otherwise so a normal test run never rewrites the goldens --
// regenerating them against a newer writer would silently destroy the very
// compatibility evidence they exist to provide.
func TestGenerateV7Fixtures(t *testing.T) {
	if os.Getenv("SIMDLOGS_WRITE_V7_FIXTURES") == "" {
		t.Skip("set SIMDLOGS_WRITE_V7_FIXTURES=1 to regenerate the v7 goldens")
	}
	dir := filepath.Join("testdata", "v7")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, c := range v7FixtureCases() {
		blob := c.group().Marshal()
		if got := get32(blob, 4); got != 7 {
			t.Fatalf("%s: writer emitted version %d, refusing to save it as a v7 golden", c.name, got)
		}
		path := filepath.Join(dir, c.name+".bin")
		if err := os.WriteFile(path, blob, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(blob))
	}
}

type v7Case struct {
	name  string
	group func() *Group
}

// The shapes worth pinning: a timestamp-only group, dictionary columns with
// one and many distinct values (different bit widths), an empty-string
// column, and a group wide enough to exercise the per-column footer loop.
func v7FixtureCases() []v7Case {
	return []v7Case{
		{"time_only", func() *Group {
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{10, 20, 30}},
			}}
		}},
		{"single_dict", func() *Group {
			d := BuildDict([]string{"info", "info", "error"})
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{1, 2, 3}},
				{Name: "level", Type: ColDict, Dict: &d},
			}}
		}},
		{"wide_dict", func() *Group {
			vals := make([]string, 500)
			for i := range vals {
				vals[i] = string(rune('a'+i%26)) + string(rune('a'+(i/26)%26)) + string(rune('0'+i%10))
			}
			d := BuildDict(vals)
			ts := make([]int64, len(vals))
			for i := range ts {
				ts[i] = int64(i) * 1000
			}
			return &Group{Rows: len(vals), Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: ts},
				{Name: "msg", Type: ColDict, Dict: &d},
			}}
		}},
		{"empty_values", func() *Group {
			d := BuildDict([]string{"", "", "x"})
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{5, 6, 7}},
				{Name: "sparse", Type: ColDict, Dict: &d},
			}}
		}},
		{"many_columns", func() *Group {
			cols := []Column{{Name: "_time", Type: ColTimestamp, Ts: []int64{1, 2}}}
			for i := 0; i < 12; i++ {
				d := BuildDict([]string{"v" + string(rune('a'+i)), "w"})
				cols = append(cols, Column{Name: "f" + string(rune('a'+i)), Type: ColDict, Dict: &d})
			}
			return &Group{Rows: 2, Columns: cols}
		}},
	}
}

// TestV7FixturesStillRead is the compatibility gate.
//
// It asserts the VALUES, not just that the bytes parse. The first version
// checked that a fixture read back with a positive row count and sane time
// bounds, which a decoder that returned garbage for every field would satisfy:
// the row count comes from the header and the time bounds from the footer, and
// neither is touched by the dictionary decode that actually reads the data.
//
// Every case in v7FixtureCases names what was written, so the expectation is
// derived from the same source the fixture was generated from rather than
// copied into a second list that can drift.
func TestV7FixturesStillRead(t *testing.T) {
	dir := filepath.Join("testdata", "v7")
	ents, err := os.ReadDir(dir)
	if err != nil {
		// NOT a skip. The fixtures are committed; their absence is a deleted
		// compatibility gate, and a gate that vanishes quietly is the failure
		// this whole file exists to prevent.
		t.Fatalf("the committed v7 fixtures are missing (%v). They are the only "+
			"evidence that a store written by an older binary still opens", err)
	}
	cases := map[string]v7Case{}
	for _, c := range v7FixtureCases() {
		cases[c.name] = c
	}

	found := map[string]bool{}
	for _, e := range ents {
		if filepath.Ext(e.Name()) != ".bin" {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".bin")
		found[name] = true
		t.Run(name, func(t *testing.T) {
			blob, err := os.ReadFile(filepath.Join(dir, e.Name()))
			if err != nil {
				t.Fatal(err)
			}
			if v := get32(blob, 4); v != 7 {
				t.Fatalf("fixture is version %d, not 7 -- it was regenerated by a "+
					"newer writer and no longer tests compatibility", v)
			}
			r, err := ReadGroup(blob)
			if err != nil {
				t.Fatalf("v7 group no longer parses: %v", err)
			}
			c, ok := cases[name]
			if !ok {
				t.Fatalf("there is a fixture on disk with no case describing it, so " +
					"nothing knows what it should contain")
			}
			want := c.group()

			if r.Rows != want.Rows {
				t.Fatalf("%d rows, want %d", r.Rows, want.Rows)
			}
			for _, col := range want.Columns {
				if col.Type == ColTimestamp {
					got := r.Timestamps(col.Name, nil, nil)
					if len(got) != len(col.Ts) {
						t.Fatalf("%s: %d timestamps, want %d", col.Name, len(got), len(col.Ts))
					}
					for i := range got {
						if got[i] != col.Ts[i] {
							t.Fatalf("%s[%d] = %d, want %d", col.Name, i, got[i], col.Ts[i])
						}
					}
					continue
				}
				// A dictionary column: every row's VALUE, which is what a
				// decoder change actually breaks.
				idx, dict := r.DictIndices(col.Name)
				if len(idx) != want.Rows {
					t.Fatalf("%s: %d indices for %d rows", col.Name, len(idx), want.Rows)
				}
				for i := 0; i < want.Rows; i++ {
					wantVal := col.Dict.Dict[col.Dict.Indices[i]]
					if int(idx[i]) >= len(dict) {
						t.Fatalf("%s[%d]: index %d is outside a dictionary of %d",
							col.Name, i, idx[i], len(dict))
					}
					if got := dict[idx[i]]; got != wantVal {
						t.Fatalf("%s[%d] = %q, want %q", col.Name, i, got, wantVal)
					}
				}
			}
		})
	}

	// Every case must have a fixture. A case added without regenerating is a
	// shape nobody is checking.
	for name := range cases {
		if !found[name] {
			t.Errorf("case %q has no committed fixture, so that shape's v7 "+
				"compatibility is untested", name)
		}
	}
	if len(found) == 0 {
		t.Fatal("no v7 fixtures on disk")
	}
}
