package storage

import (
	"os"
	"path/filepath"
	"testing"
)

// Golden v7 fixtures are captured with the CURRENT writer, before the format
// bump, and committed. After the bump the writer emits v8 and these files are
// the only proof that a store written by an older binary still opens.
//
// Run with -run TestGenerateV7Fixtures -v and the env var set:
//
//	SIMDLOGS_WRITE_V7_FIXTURES=1 go test ./internal/storage -run TestGenerateV7Fixtures
//
// It is skipped otherwise so a normal test run never rewrites the goldens --
// regenerating them against a newer writer would silently destroy the very
// compatibility evidence they exist to provide.
func TestGenerateV7Fixtures(t *testing.T) {
	if os.Getenv("SIMDLOGS_WRITE_V7_FIXTURES") == "" {
		t.Skip("set SIMDLOGS_WRITE_V7_FIXTURES=1 to regenerate the v7 goldens")
	}
	dir := filepath.Join("testdata", "v7")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, c := range v7FixtureCases() {
		blob := c.group().Marshal()
		if got := get32(blob, 4); got != 7 {
			t.Fatalf("%s: writer emitted version %d, refusing to save it as a v7 golden", c.name, got)
		}
		path := filepath.Join(dir, c.name+".bin")
		if err := os.WriteFile(path, blob, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(blob))
	}
}

type v7Case struct {
	name  string
	group func() *Group
}

// The shapes worth pinning: a timestamp-only group, dictionary columns with
// one and many distinct values (different bit widths), an empty-string
// column, and a group wide enough to exercise the per-column footer loop.
func v7FixtureCases() []v7Case {
	return []v7Case{
		{"time_only", func() *Group {
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{10, 20, 30}},
			}}
		}},
		{"single_dict", func() *Group {
			d := BuildDict([]string{"info", "info", "error"})
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{1, 2, 3}},
				{Name: "level", Type: ColDict, Dict: &d},
			}}
		}},
		{"wide_dict", func() *Group {
			vals := make([]string, 500)
			for i := range vals {
				vals[i] = string(rune('a'+i%26)) + string(rune('a'+(i/26)%26)) + string(rune('0'+i%10))
			}
			d := BuildDict(vals)
			ts := make([]int64, len(vals))
			for i := range ts {
				ts[i] = int64(i) * 1000
			}
			return &Group{Rows: len(vals), Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: ts},
				{Name: "msg", Type: ColDict, Dict: &d},
			}}
		}},
		{"empty_values", func() *Group {
			d := BuildDict([]string{"", "", "x"})
			return &Group{Rows: 3, Columns: []Column{
				{Name: "_time", Type: ColTimestamp, Ts: []int64{5, 6, 7}},
				{Name: "sparse", Type: ColDict, Dict: &d},
			}}
		}},
		{"many_columns", func() *Group {
			cols := []Column{{Name: "_time", Type: ColTimestamp, Ts: []int64{1, 2}}}
			for i := 0; i < 12; i++ {
				d := BuildDict([]string{"v" + string(rune('a'+i)), "w"})
				cols = append(cols, Column{Name: "f" + string(rune('a'+i)), Type: ColDict, Dict: &d})
			}
			return &Group{Rows: 2, Columns: cols}
		}},
	}
}

// TestV7FixturesStillRead is the compatibility gate. It runs on every normal
// test run: the committed v7 bytes must keep parsing, and must keep giving
// the same row count and time bounds, whatever version the writer emits now.
func TestV7FixturesStillRead(t *testing.T) {
	dir := filepath.Join("testdata", "v7")
	ents, err := os.ReadDir(dir)
	if err != nil {
		t.Skipf("no v7 fixtures yet: %v", err)
	}
	n := 0
	for _, e := range ents {
		if filepath.Ext(e.Name()) != ".bin" {
			continue
		}
		n++
		blob, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if v := get32(blob, 4); v != 7 {
			t.Fatalf("%s: fixture is version %d, not 7 -- it was regenerated by a newer writer and no longer tests compatibility", e.Name(), v)
		}
		r, err := ReadGroup(blob)
		if err != nil {
			t.Fatalf("%s: v7 group no longer parses: %v", e.Name(), err)
		}
		if r.Rows <= 0 {
			t.Fatalf("%s: parsed %d rows", e.Name(), r.Rows)
		}
		if r.TimeMax < r.TimeMin {
			t.Fatalf("%s: time bounds [%d, %d]", e.Name(), r.TimeMin, r.TimeMax)
		}
	}
	if n == 0 {
		t.Skip("no v7 fixtures committed yet")
	}
}
